### ISSUE TITLE
-n flag to check syntax

### ISSUE THREAD

**Issue by mcandre** [JNeitzel/v6shell#3]
Could tsh and etsh get `-n` flags that emit non-zero exit status code when a script is provided that doesn't match the Thompson sh AST? I doubt many people are linting Thompson sh scripts these days, but such an option would still be useful to help separate Thompson sh scripts from POSIX sh scripts.

**Comment by JNeitzel** [comment]
Hello @mcandre,

Pardon the delay. I was thinking I'd get notified for issues, but somehow it didn't happen. In any case, with regard to your issue / feature request...

For tsh, it's not possible for compatibility reasons of course. But for etsh, it's quite possible, and good idea in fact. Thank you. So, I'll see about adding a -n / noexec flag to etsh / osh.c (tonight if possible).

Regards,
Jeff

**Comment by JNeitzel** [comment]
Fixed.
